name: feedplay
description:  FeedPlay - HTML5 Games App
publish_to: 'none'
version: 1.0.0+FP-1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.6.0
  webview_flutter: ^4.4.2
  cached_network_image: ^3.3.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  url_launcher: ^6.2.4
  shared_preferences: ^2.2.2
  google_mobile_ads: ^6.0.0
  share_plus: ^12.0.1
  flutter_inappwebview: ^6.1.5
  package_info_plus: ^8.0.0
  path_provider: ^2.1.5
  connectivity_plus: ^6.0.3
  in_app_update: ^4.2.2
  in_app_review: ^2.0.0

  web: ^1.1.1

dependency_overrides:
  connectivity_plus: ^6.0.3
  sqflite_android: 2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:

    - assets/html5.json
    - assets/icon.png
    - assets/splash.png
    - assets/co_splash.png
    - assets/free-earn.png